import Link from "next/link";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Next Portfolio site!",
  description: "Generated by Next and Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header>
          <Link
            href="/"
            className="bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Evan
          </Link>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
